services:
  - type: web
    name: letcpp
    env: static
    buildCommand: npm run build:render
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html